version: '3.4'

services:
  jacms.content.api:
    image: ${DOCKER_REGISTRY-}jacmscontentapi
    build:
      context: .
      dockerfile: JACMS.Content.API/Dockerfile
  db:
    image: 'mariadb:latest'
    restart: always
    volumes:
        - ./sql-dump:/docker-entrypoint-initdb.d
    environment:
        MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
        MARIADB_USER: "${dbuser}"
        MARIADB_PASSWORD: "${dbpass}"
        MARIADB_DATABASE: "jacms"
    ports:
        - 3306:3306