<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Exceptions\" />
    <Folder Include="Helpers\" />
    <Folder Include="Services\Abstractions\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DataAccess\JACMS.API.DataAccess.Core\JACMS.API.DataAccess.Core.csproj" />
    <ProjectReference Include="..\..\DataAccess\JACMS.API.DataAccess.PostgreSQL\JACMS.API.DataAccess.PostgreSQL.csproj" />
  </ItemGroup>

</Project>
