version: '3.4'

services:
  jacms.content.api:
    image: ${DOCKER_REGISTRY-}jacmscontentapi
    build:
      context: .
      dockerfile: JACMS.Content.API/Dockerfile
    ports:
        - 4280:80
        - 4242:443
    depends_on:
        - db
        - documentDb
        - cache
  db:
    image: 'mariadb:latest'
    restart: always
    volumes:
        - ../../sql-dump:/docker-entrypoint-initdb.d
    environment:
        MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
        MARIADB_USER: "${dbuser}"
        MARIADB_PASSWORD: "${dbpass}"
        MARIADB_DATABASE: "${database}"
    ports:
        - 3306:3306
  documentDb:
    image: mongo
    restart: always
    ports:
        - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${mongoUn}"
      MONGO_INITDB_ROOT_PASSWORD: "${mongoPw}"
  cache:
    image: redis
    restart: always
    ports:
        - 6379:6379
  jacms.content.pagebuilder:
    image: ${DOCKER_REGISTRY-}jacmscontentpagebuilder
    build:
      context: ..
      dockerfile: Services/JACMS.Content.PageBuilder/Dockerfile
    depends_on:
        - jacms.content.api
        - documentDb
        - db