-- Table: Identity.RoleClaims

-- DROP TABLE IF EXISTS "Identity"."RoleClaims";

CREATE TABLE IF NOT EXISTS "Identity"."RoleClaims"
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" bigint NOT NULL,
    "ClaimType" text COLLATE pg_catalog."default",
    "ClaimValue" text COLLATE pg_catalog."default",
    "IsDeleted" boolean NOT NULL,
    "CreationDate" timestamp without time zone NOT NULL,
    "UpdateDate" timestamp without time zone NOT NULL,
    CONSTRAINT "RoleClaims_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoleClaims_Role" FOREIGN KEY ("RoleId")
        REFERENCES "Identity"."Role" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS "Identity"."RoleClaims"
    OWNER to "JACMSUser";