-- Table: Identity.Role

--DROP TABLE IF EXISTS "Identity"."Role";

CREATE TABLE IF NOT EXISTS "Identity"."Role"
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(256) COLLATE pg_catalog."default",
    "NormalizedName" character varying(256) COLLATE pg_catalog."default",
    "ConcurrencyStamp" text COLLATE pg_catalog."default",
    "IsDeleted" boolean NOT NULL,
    "CreationDate" timestamp without time zone NOT NULL,
    "UpdateDate" timestamp without time zone NOT NULL,
    CONSTRAINT "Role_pkey" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS "Identity"."Role"
    OWNER to "JACMSUser";