-- Table: Identity.UserClaims

-- DROP TABLE IF EXISTS "Identity"."UserClaims";

CREATE TABLE IF NOT EXISTS "Identity"."UserClaims"
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "ClaimType" text COLLATE pg_catalog."default",
    "ClaimValue" text COLLATE pg_catalog."default",
    "IsDeleted" boolean NOT NULL,
    "CreationDate" timestamp without time zone NOT NULL,
    "UpdateDate" timestamp without time zone NOT NULL,
    CONSTRAINT "UserClaims_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserClaim_User" FOREIGN KEY ("UserId")
        REFERENCES "Identity"."User" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS "Identity"."UserClaims"
    OWNER to "JACMSUser";